apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip
  labels:
    app: geoip
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: geoip
  template:
    metadata:
      labels:
        app: geoip
    spec:
      tolerations:
      - key: "gke-preemptible"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: In
                values:
                - "true"
      containers:
        - name: geoip
          image: melalj/geoip-api
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "50m"
              memory: "100Mi"
            requests:
              cpu: "40m"
              memory: "20Mi"
          livenessProbe:
            httpGet:
              path: /1.1.1.1
              port: 5000
            initialDelaySeconds: 60
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: geoip
spec:
  ports:
  - port: 5000
    targetPort: 5000
    name: http
  selector:
    app: geoip
